#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/area_or_perimeter/solution.js /Users/pepellou/Workspace/codewars/katas/area_or_perimeter/tests.js
