#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/how_many_are_smaller_than_me/solution.js /Users/pepellou/Workspace/codewars/katas/how_many_are_smaller_than_me/tests.js
