#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/diagonals_sum/solution.js /Users/pepellou/Workspace/codewars/katas/diagonals_sum/tests.js
