#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/where_is_my_parent/solution.js /Users/pepellou/Workspace/codewars/katas/where_is_my_parent/tests.js
