#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/backspaces_in_string/solution.js /Users/pepellou/Workspace/codewars/katas/backspaces_in_string/tests.js
