#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/quick_n_choose_k_calculator/solution.js /Users/pepellou/Workspace/codewars/katas/quick_n_choose_k_calculator/tests.js
