#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/prize_draw/solution.js /Users/pepellou/Workspace/codewars/katas/prize_draw/tests.js
