#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/testing_1_2_3/solution.js /Users/pepellou/Workspace/codewars/katas/testing_1_2_3/tests.js
