#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Title of the kata (human readable):"
read title
echo ''

echo "Folder name (no spaces, please):"
read folder
echo ''

echo "Url of kata:"
read url
echo ''

mkdir $DIR/$folder

echo '#!/bin/bash' > $DIR/$folder/test
echo 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"' >> $DIR/$folder/test
echo '' >> $DIR/$folder/test
echo '$DIR/../test $DIR' >> $DIR/$folder/test
chmod a+x $DIR/$folder/test

echo '#!/bin/bash' > $DIR/$folder/work
echo 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"' >> $DIR/$folder/work
echo '' >> $DIR/$folder/work
echo 'vi -o '$DIR/$folder'/solution.js '$DIR/$folder'/tests.js' >> $DIR/$folder/work
chmod a+x $DIR/$folder/work

echo 'const multiply = (a, b) => {' > $DIR/$folder/solution.js
echo '    return a * b;' >> $DIR/$folder/solution.js
echo '}' >> $DIR/$folder/solution.js

echo 'const chai = require("chai");' > $DIR/$folder/tests.js
echo 'const assert = chai.assert;' >> $DIR/$folder/tests.js
echo '' >> $DIR/$folder/tests.js
echo 'const tests = [' >> $DIR/$folder/tests.js
echo '  [ 0,   1,    0],' >> $DIR/$folder/tests.js
echo '  [16,   2,   32],' >> $DIR/$folder/tests.js
echo '  [70,  -1,  -70],' >> $DIR/$folder/tests.js
echo '  [26, -26, -676],' >> $DIR/$folder/tests.js
echo '];' >> $DIR/$folder/tests.js
echo '' >> $DIR/$folder/tests.js
echo 'describe("Tests", function() {' >> $DIR/$folder/tests.js
echo '  for (const [a, b, expected] of tests) {' >> $DIR/$folder/tests.js
echo '    it(`input: ${a}, ${b}`, function() {' >> $DIR/$folder/tests.js
echo '      assert.strictEqual(multiply(a, b), expected);' >> $DIR/$folder/tests.js
echo '    });' >> $DIR/$folder/tests.js
echo '  }' >> $DIR/$folder/tests.js
echo '});' >> $DIR/$folder/tests.js

echo '- '$title' [description]('$url') [solution]('$folder'/solution.js)' >> $DIR/README.md
