#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function test_kata() {
    kata=$1

    tempFile=$DIR/tmpFileWithAVeryLongName_ifYouSeeThisFile_Please_DeleteIt.js

    cat $kata/solution.js > $tempFile
    cat $kata/tests.js >> $tempFile

    mocha $tempFile

    rm $tempFile
}

kata=$1

if [ -z "$kata" ]
then
    for kata in `ls katas`
    do
        test_kata katas/$kata
    done
else
    test_kata $kata
fi

