#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/string_array_duplicates/solution.js /Users/pepellou/Workspace/codewars/katas/string_array_duplicates/tests.js
