#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/character_with_longest_consecutive_repetition/solution.js /Users/pepellou/Workspace/codewars/katas/character_with_longest_consecutive_repetition/tests.js
