#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/scheduling_SJF/solution.js /Users/pepellou/Workspace/codewars/katas/scheduling_SJF/tests.js
