#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/simple_assembler_interpreter/solution.js /Users/pepellou/Workspace/codewars/katas/simple_assembler_interpreter/tests.js
