#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/equal_sides_of_an_array/solution.js /Users/pepellou/Workspace/codewars/katas/equal_sides_of_an_array/tests.js
