#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/unique_digits_sequence/solution.js /Users/pepellou/Workspace/codewars/katas/unique_digits_sequence/tests.js
