#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/perimeter_squares_in_rectangle/solution.js /Users/pepellou/Workspace/codewars/katas/perimeter_squares_in_rectangle/tests.js
