#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/array_helpers/solution.js /Users/pepellou/Workspace/codewars/katas/array_helpers/tests.js
