#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/shortest_knight_path/solution.js /Users/pepellou/Workspace/codewars/shortest_knight_path/tests.js
