#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/sum_the_tree/solution.js /Users/pepellou/Workspace/codewars/katas/sum_the_tree/tests.js
