#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/running_out_of_space/solution.js /Users/pepellou/Workspace/codewars/katas/running_out_of_space/tests.js
