#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/regex_password_validation/solution.js /Users/pepellou/Workspace/codewars/katas/regex_password_validation/tests.js
