#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/help_the_bookseller/solution.js /Users/pepellou/Workspace/codewars/help_the_bookseller/tests.js
