#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/manhattan_distance/solution.js /Users/pepellou/Workspace/codewars/katas/manhattan_distance/tests.js
