#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/parseInt_reloaded/solution.js /Users/pepellou/Workspace/codewars/katas/parseInt_reloaded/tests.js
