#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/oneliner_countdown_2/solution.js /Users/pepellou/Workspace/codewars/oneliner_countdown_2/tests.js
