#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/last_digit_of_a_huge_number/solution.js /Users/pepellou/Workspace/codewars/katas/last_digit_of_a_huge_number/tests.js
