#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/16_plus_18_is_214/solution.js /Users/pepellou/Workspace/codewars/katas/16_plus_18_is_214/tests.js
