#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/split_by_value/solution.js /Users/pepellou/Workspace/codewars/katas/split_by_value/tests.js
