#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/math_issues/solution.js /Users/pepellou/Workspace/codewars/katas/math_issues/tests.js
