#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/multiplicative_persistence/solution.js /Users/pepellou/Workspace/codewars/katas/multiplicative_persistence/tests.js
