#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/word_values/solution.js /Users/pepellou/Workspace/codewars/katas/word_values/tests.js
