#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/number_of_trailing_zeros_of_n_factorial/solution.js /Users/pepellou/Workspace/codewars/number_of_trailing_zeros_of_n_factorial/tests.js
