#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/counting_duplicates/solution.js /Users/pepellou/Workspace/codewars/counting_duplicates/tests.js
