#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/sort_strings_by_most_contiguous_vowels/solution.js /Users/pepellou/Workspace/codewars/katas/sort_strings_by_most_contiguous_vowels/tests.js
