#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vi -o /Users/pepellou/Workspace/codewars/katas/string_evens_characters/solution.js /Users/pepellou/Workspace/codewars/katas/string_evens_characters/tests.js
